# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - id: "gdl"
    main: ./cli/main.go
    binary: gdl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: "gdl"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}"
